# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: jekyll-agency

url    : "https://johnarmasq.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/jubilant-octo-giggle" # the subpath of your site, e.g. /blog

title      : Sonorum | Academia de música online
name       : Sonorum
email      : sonorumacademy@gmail.com #this is also the email contact forms will go to
description: "Inscríbete y empieza a disfrutar de una experiencia musical maravillosa."
author     : Jonathan Armas-Eliana Cudriz
logo:     #optional, defaults to site title
  path: assets\img\logo.png
  height: 25 #height in px, defaults to 52px
  alt: Logo Sonorum Academy
whatsapp: https://api.whatsapp.com/send/?phone=573053491660&text=¡Hola!+Estoy+interesado+en+las+clases+de+

permalink: /:title/

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"
